project:
  type: book
  output-dir: docs

book:
  title: "Computational Cognitive Models"
  author: "Gregory E. Cox"
  date: "2/11/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - ebrw.qmd
    - r_coding.qmd
    - random_walk.qmd
    - diffusion_sim.qmd
    - diffusion_fit.qmd
    # - blast_example.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: pulse
    code-fold: true

editor: source