project:
  type: book
  output-dir: docs

book:
  title: "Computational Cognitive Modeling"
  author: "Gregory E. Cox"
  # date: "3/4/2025"
  chapters:
    - index.qmd
    - part: "Background"
      chapters:
        - intro.qmd
        - r_coding.qmd
    - part: "Modeling behavior"
      chapters:
        - random_walk.qmd
        - diffusion_sim.qmd
        - diffusion_fit.qmd
        - model_comparison.qmd
        - blast_example.qmd
        - accumulator_models.qmd
    - part: "Coupling behavior to structured representations"
      chapters:
        - ebrw.qmd
        - vector_reps.qmd
        - learning.qmd
        - backprop.qmd
    - part: "Cognitive models at larger and smaller scales"
      chapters:
        - agent_based_models.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: pulse
    code-fold: true

execute:
  cache: false

editor: source